### ISSUE TITLE
No Login page

### ISSUE THREAD

**Issue by Rock0007** [SpandanM110/Metamask-React-Login#1]
![image](https://github.com/SpandanM110/Metamask-React-Login/assets/78554483/4b410044-97ca-49ee-9594-4b1f76ab11dd)

I don't see any Login page after ```npm start```. It's directly taking me to 👆 page.  And there are no Login routes

**Comment by SpandanM110** [comment]
It's actually a web3 login just kept the code for future instances.

**Comment by Rock0007** [comment]
> It's actually a web3 login just kept the code for future instances.

can i put my hands to involve in this project  ?
